spring.application.name=gateway
server.port=${SERVER_PORT:8086}

spring.graphql.path=/graphql

management.otlp.metrics.export.enabled=${OTLP_METRICS_EXPORT_ENABLED:false}
management.tracing.sampling.probability=${OTLP_TRACING_SAMPLING:1.0}
logging.structured.format.console=logstash

app.security.enabled=${APP_SECURITY_ENABLED:true}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://keycloak:8080/realms/LoCarE}

app.downstream.vehicules-url=${VEHICULES_GRAPHQL_URL:http://localhost:8081/graphql}
app.downstream.conducteurs-url=${CONDUCTEURS_GRAPHQL_URL:http://localhost:8082/graphql}
app.downstream.maintenance-url=${MAINTENANCE_GRAPHQL_URL:http://localhost:8085/graphql}
