app.security.enabled=false
app.downstream.vehicules-url=http://localhost:8081/graphql
app.downstream.conducteurs-url=http://localhost:8082/graphql
app.downstream.maintenance-url=http://localhost:8085/graphql
